2024-07-06 17:47:20.006 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-07-06 18:28:25.507 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xDB7E)
2024-07-07 02:08:16.896 WARNING (MainThread) [homeassistant.components.dlna_dms] Failed connecting to recently alive device at http://[fe80::83e8:3d6c:14b8:b63b%2]:2869/upnphost/udhisapi.dll?content=uuid:d3613ba9-d94a-4550-b274-d939091a79d2: UpnpConnectionError("ClientConnectorError(ConnectionKey(host='fe80::83e8:3d6c:14b8:b63b%2', port=2869, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=-8709351163568846343), OSError('Domain name not found'))", None)
2024-07-07 13:07:54.933 ERROR (MainThread) [homeassistant.components.ipp.coordinator] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.
